-- MySQL Script generated by MySQL Workbench
-- 05/29/19 23:19:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movie_cruiser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_cruiser
-- -----------------------------------------------------
CREATE SCHEMA `movie_cruiser` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `movie_cruiser` ;

-- -----------------------------------------------------
-- Table `movie_cruiser`.`user`
-- -----------------------------------------------------
CREATE TABLE `movie_cruiser`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(60) NULL,
  `us_first_name` VARCHAR(60) NULL,
  `us_last_name` VARCHAR(60) NULL,
  `us_password` VARCHAR(60) NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_cruiser`.`movie_list`
-- -----------------------------------------------------
CREATE TABLE  `movie_cruiser`.`movie_list` (
  `mo_id` INT NOT NULL AUTO_INCREMENT,
  `mo_title` VARCHAR(100) NULL,
  `mo_box_office` BIGINT NULL,
  `mo_active` VARCHAR(3) NULL,
  `mo_date_of_launch` DATE NULL,
  `mo_genre` VARCHAR(45) NULL,
  `mo_has_teaser` VARCHAR(3) NULL,
  `mo_image`VARCHAR(10000)NULL,
  `mo_description`TEXT NULL,
  `mo_rating`VARCHAR(60)NULL,
  `mo_language`VARCHAR(60)NULL,
  `mo_runtime`VARCHAR(60)NULL,
  `mo_like`VARCHAR(60)NULL,
  `mo_trailer`VARCHAR(60)NULL,
  PRIMARY KEY (`mo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_cruiser`.`favoritefavoritemovie_listuser`
-- -----------------------------------------------------
CREATE TABLE  `movie_cruiser`.`favorite` (
  `fa_id` INT NOT NULL AUTO_INCREMENT,
  `fa_us_id` INT NULL,
  `fa_mo_id` INT NULL,
  PRIMARY KEY (`fa_id`),
  INDEX `fa_us_fk_idx` (`fa_us_id` ASC),
  INDEX `fa_mo_fk_idx` (`fa_mo_id` ASC),
  CONSTRAINT `fa_us_fk`
    FOREIGN KEY (`fa_us_id`)
    REFERENCES `movie_cruiser`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fa_mo_fk`
    FOREIGN KEY (`fa_mo_id`)
    REFERENCES `movie_cruiser`.`movie_list` (`mo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `movie_cruiser`.`role`
-- -----------------------------------------------------
CREATE TABLE  `movie_cruiser`.`role` (
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `movie_cruiser`.`user_role`
-- -----------------------------------------------------
CREATE TABLE  `movie_cruiser`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_us_id` INT NULL,
  `ur_ro_id` INT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `ur_us_fk_idx` (`ur_us_id` ASC),
  INDEX `ur_ro_fk_idx` (`ur_ro_id` ASC),
  CONSTRAINT `ur_us_fk`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `movie_cruiser`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_ro_fk`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `movie_cruiser`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `movie_cruiser`.`genre`
-- -----------------------------------------------------
CREATE TABLE  `movie_cruiser`.`genre` (
  `ge_id` INT NOT NULL AUTO_INCREMENT,
  `ge_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ge_id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


use movie_cruiser;
insert into movie_list(mo_id, mo_title, mo_box_office, mo_active, mo_date_of_launch, mo_genre, mo_has_teaser,mo_image,mo_description,mo_rating,mo_language,mo_runtime,mo_like,mo_trailer)
values(1,'Avatar',2787965087,'Yes','2017/03/15','Science Fiction','Yes','https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg',
'Avatar is a science fiction film written and directed by James Cameron. In this movie Jake, a paraplegic marine, replaces his brother on the Navi
 inhabited Pandora for a corporate mission.He is accepted by the natives as one of their own but he must decide where his loyalties lie.
 His choice of Loyatily is the major turn in the movie','U/A','English','2.41.44','88','https://www.youtube.com/embed/5PSNL1qE6VY'),
(2,'The Avengers',1518812988,'Yes','2017/12/23','Superhero','No','https://cdn.shopify.com/s/files/1/1148/2822/products/PBMAAOU088_1024x1024.jpg?v=1510903066',
'The Marvel Cinematic Universe (MCU) films are a series of American superhero films producedby Marvel Studios based on characters that appear in publications 
 by Marvel Comics.The MCU is the shared universe in which all of the films are set.It is a superhero movie based on Adventures','U/A','English','2.23.00','90',
 'https://www.youtube.com/embed/eOrNdBpGMv8'),
(3,'Titanic',2187463944,'Yes','2017/08/21','Romance','No','https://upload.wikimedia.org/wikipedia/en/1/19/Titanic_%28Official_Film_Poster%29.png',
'Seventeen-year-old Rose hails from an aristocratic family and is set to be marriedWhen she boards the Titanic, she meets Jack Dawson, an artist,
 and falls in love with him.The director felt a love story interspersed with the human loss would be essential to convey the emotional impact of the disaster.',
 'A','English','3.15.00','95','https://www.youtube.com/embed/2e-eXJ6HgkQ'),
(4,'Jurassic World',1671713208,'No','2017/07/02','Science Fiction','Yes','https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/jurassic-world-5-movie-poster-prints.jpg',
'The Jurassic World luxury resort provides a habitat for an array of genetically engineered dinosaursincluding the vicious and intelligent Indominus rex.
 When the massive creature escapes,causes disaster Now, it is up to a former military man and animal expert (Chris Pratt) to use his special skills to save the people.',
'U','English','2.4.00','80','https://www.youtube.com/embed/RFinNxS5KN4'),
(5,'Avengers:End Game',2750760348,'Yes','2022/11/02','Superhero','Yes','https://img.purch.com/o/aHR0cDovL3d3dy5uZXdzYXJhbWEuY29tL2ltYWdlcy9pLzAwMC8yNTMvMDQ3L2kwMi9FbmRnYW1lX09kZW9uX0xlZnQuanBlZw==',
'Thanos used the Infinity Gauntlet to disintegrate half of all life in the universeTony Stark and Nebula from deep space and returns them to Earth
 where they reunite with the remaining Avengers.They plan to retake and use the Infinity Stones to reverse the Snap but Thanos reveals he destroyed the Stones 
 to prevent their further use','U','English','3.2.00','92','https://www.youtube.com/embed/TcMBFSGVi1c');

insert into user(us_name,us_password,us_first_name,us_last_name)
values('admin','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','admin','admin'),('user','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','user','user');

insert into role(ro_name)
values('admin'),('user');

insert into user_role(ur_us_id,ur_ro_id)
values(1,1),(2,2);

insert into genre(ge_name)
values('Superhero'),('Romance'),('Science Fiction'),('Adventure'),('Comedy');




